# Generated by Django 4.0.6 on 2022-07-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-name']},
        ),
    ]
